# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu: "Releases"

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
version: "v0.10.0"

archived_version: true
url_latest_version: https://projectcapsule.dev
versions:
- version: v0.10.0
  url: https://projectcapsule.dev
#- version: v0.10.0
#  url: https://release-0-10-0.projectcapsule.dev