root_dir = "content/en"
fallback_extensions = ["md", "html"]
exclude = [
  "https://goteleport.com/", # Teleport always returns 403, even it is available
  "https://docs.redhat.com/", # Red Hat docs return 403 to bots
  "https://issues.redhat.com/", # Red Hat issue tracker returns 403 to bots
]
exclude_path = ["public/docs/reference/"]
